#!/bin/bash
#
# ohlog <recipient>
#
# sends an email using the configured
# smtp server.
today=$(date "+%-d %B, %Y")
subject="It's $today - How did your day go?"
body="Just reply to this email with your entry."
to="$1"
sendmail -t <<EOF
Subject: $subject
To: $to

$body
EOF
