#!/bin/bash
#
# ohlog <recipient>
#
# sends an email using the configured
# smtp server.
today=$(date "+%-d %B, %Y")
subject="It's $today - How did your day go?"
body="Just reply to this email with your entry."
email="$1"
sendmail "$email" <<EOF
Subject: $subject

$body
EOF
